name: Unity Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v4

      # Cache the Library folder to speed up subsequent builds
      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-Unity6-${{ github.sha }}
          restore-keys: |
            Library-${{ runner.os }}-Unity6-

      # Build the Unity project for Linux (headless) using the GameCI builder
      - name: Build with Unity
        uses: game-ci/unity-builder@v4
        env:
          # These secrets should be added in the repository settings
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          unityVersion: 6000.0.58f1
          targetPlatform: StandaloneLinux64

      # Upload the build output as a workflow artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UnityBuild
          path: build
